name: "Verify FHIR Profiles"
description: "Verify FHIR profiles using the Java FHIR validator"
inputs:
  fhir-version:
    description: "Version FHIR to be validated against"
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "17"
    - run: wget -q https://github.com/hapifhir/org.hl7.fhir.core/releases/latest/download/validator_cli.jar
      shell: bash
    - run: java -jar validator_cli.jar -html-output validation.html -version ${{ inputs.fhir-version }} fsh-generated/resources
      shell: bash
    - if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: Validation
        path: validation.html
